language: php

php:
  - 5.6
  - 7.0

before_script:
  - mysql -e "CREATE DATABASE `angel_test`;"
  - cp .env.travis .env
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  - php artisan key:generate

script:
  - vendor/bin/phpunit