language: php

php:
  - 5.6
  - 7.0

before_script:
  - mysql -e "CREATE DATABASE angel_test;"
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  - npm install -g bower
  - npm install
  - bower install
  - gulp
  - cp .env.travis .env
  - php artisan key:generate

script:
  - gulp
  - vendor/bin/phpunit